### ISSUE TITLE
Unhandled Rejection (Error): Local storage is missing an ID Token, Please authenticate

### ISSUE THREAD

**Issue by JoeSpencer** [richardzcode/Journal-AWS-Amplify-Tutorial#4]
Getting this error from the LoginForm.js at line 37

Everytime a user logs in, a new 2 factor auth code is sent to phone. Im not sure if the 2 errors are related.

Did I miss something?

**Comment by richardzcode** [comment]
@JoeSpencer this looks like an old issue of aws-amplify. I've updated package.json to have latest aws-amplify and aws-amplify-react.

Could you try update your libraries to see if problem persists?

```
npm install aws-amplify@latest
npm install aws-amplify-react@latest
```

BTW it appears the latest aws-amplify-react have issue related to federated signIn. I'll make a PR there hopefully to resolve it quickly.

**Comment by JoeSpencer** [comment]
@richardzcode Should I enter an actual Facebook app id or can it run with the placeholder?

**Comment by richardzcode** [comment]
You can remove `<Federated ... />` from `render` if don't want to support Facebook signIn. Otherwise you'll need to have an actual Facebook app id for it to work. Placeholder doesn't break normal signIn though.

**Comment by richardzcode** [comment]
@JoeSpencer Glad the project helps :)

One of the goals of [aws-amplify](https://github.com/aws/aws-amplify) was to seamlessly work with both browser and native JS frameworks. The core library, `aws-amplify`, hides away platform implementation details. Then framework specific libraries, like `aws-amplify-react` and `aws-amplify-react-native`, provide framework specific helpers.

So should be no conflicts, but need to replace `aws-amplify-react` with `aws-amplify-react-native` when doing react-native development.
