### ISSUE TITLE
Issue with Latest versions for aws amplify

### ISSUE THREAD

**Issue by yalamber** [richardzcode/Journal-AWS-Amplify-Tutorial#5]
Hello, 
I tried running this app with latest versions of aws amplify. 1.0.4. I encountered following issues. 
1. Greetings do not update after login.
2. even when logged in if we go to the login page it shows login form for brief seconds before showing After login component.

**Comment by richardzcode** [comment]
hey @yalamber yes Amplify 1.0.0 is a breaking update. I will look into this later. Thank you!

**Comment by richardzcode** [comment]
Hey @yalamber sorry for the long delay. FYI I am updating the tutorial with Amplify 1.1. Authentication part is finished. With help of `Hub` it is actually much simpler for getting notified by login action.

**Comment by richardzcode** [comment]
The whole tutorial is rewritten
