### ISSUE TITLE
Broken links on deployed site

### ISSUE THREAD

**Issue by trybick** [richardzcode/Journal-AWS-Amplify-Tutorial#6]
Hey there,

The links on for "Step 01", "Step 02", etc don't work currently on the site [https://richardzcode.github.io/Journal-AWS-Amplify-Tutorial/](https://richardzcode.github.io/Journal-AWS-Amplify-Tutorial/).

Looks like the steps are in your ReadMe, but just letting you know.

Thanks-
Tim

**Comment by richardzcode** [comment]
Thank you @trybick! The site is outdated. I need to fix it... Thank you for reminding me!

**Comment by trybick** [comment]
Do you need any help with this site or documentation? I'm looking for projects to help with.

**Comment by richardzcode** [comment]
The original site was from experimentation of a documentation generating tool. I've changed it back to GitHub default. But yes, It'll be great to get help on.

**Comment by trybick** [comment]
@richardzcode What are looking for help on specifically?

**Comment by richardkeller411** [comment]
There should be a GitHub with Completed Tutorial.
